apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gkereggff-nodejs
  janus-idp.io/tekton: gkereggff-nodejs
  backstage.io/kubernetes-id: gkereggff-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gkereggff-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
